name: 'issue-comment-translator'
on: 
  issue_comment: 
    types: [created]
  issues: 
    types: [opened]

jobs:
  build:
    runs-on: [self-hosted, macOS, dev-runner]
    steps:
      - uses: tomsun28/issues-translate-action@v2.5
